version: 2

models:
  - name: keyword_analysis
    description: "This model counts the monthly mentions a the keyword (here duckdb) in the title or text of Hacker News posts, organized by year and month."
  - name: most_monthly_voted_stories
    description: "This model determines the most voted story for each month."
  - name: most_commented_stories_each_month
    description: "This model calculates the total number of comments for each story and identifies the most commented story of each month."
  - name: most_shared_websites
    description: "This model returns the top domains being shared on Hacker News."
