version: 2

models:
  - name: sentiment_nsfw
    description: 'Table capturing sentiment analysis and NSFW indicators'
    columns:
      - name: row_number
        description: 'Row number of the reddit_data'
        tests:
          - unique
          - not_null
      - name: sentiment_tone
        description: 'Tone of the sentiment (e.g., humorous)'
      - name: sentiment_magnitude
        description: 'Magnitude of the sentiment'
      - name: nsfw
        description: 'Indicates if content is NSFW or not'
        tests:
          - accepted_values:
              values: [true, false]

  - name: topics_nouns_products
    description: 'Table capturing main topics, important nouns, and products'
    columns:
      - name: id
        description: 'Unique identifier for each row'
        tests:
          - unique
          - not_null
      - name: row_number
        description: 'Row number of the reddit_data'
        tests:
          - not_null
      - name: type
        description: 'Type of the entry (main_topic, important_noun, or product)'
        tests:
          - accepted_values:
              values: ['main_topic', 'important_noun', 'product','human']
      - name: value
        description: 'The actual topic, noun, or product'
        tests:
          - not_null

    config:
      materialized: 'table'