version: 2

models:
  - name: inter_yt_country
    description: distinct country from youtube country
    columns:
      - name: country_code
        description: 2 letters country_code
      - name: country_desc
        description: full country name

  - name: inter_yt_channel
    description: trending channel on Youtube
    columns:
      - name: channel_id
        description: channel identifier
      - name: channel_title
        description: channel title